#!/usr/bin/env python3
"""Build a conservative, receiver-specific XMLTV guide from public feeds.

Only channels in the receiver's Nilesat bouquet are emitted. A channel is
included only when its name has an unambiguous exact normalized match and its
feed contains a real, current programme. Unmatched channels are reported.
"""

import argparse
import collections
import datetime as dt
import gzip
import json
import re
import unicodedata
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path


FEEDS = [
    ("Arabic elCinema", "https://raw.githubusercontent.com/GhalebAldoboni/EPG-Guide/master/ArabicEPG.xml"),
    ("IPTV EPG Egypt", "https://iptv-epg.org/files/epg-eg.xml.gz"),
    ("IPTV EPG Saudi", "https://iptv-epg.org/files/epg-sa.xml.gz"),
    ("IPTV EPG UAE", "https://iptv-epg.org/files/epg-ae.xml.gz"),
]
PLACEHOLDERS = {"", "no data", "no game today", "جدول البرامج غير متاح"}


def key(name):
    name = unicodedata.normalize("NFKC", name).casefold()
    name = re.sub(r"^(?:eg|sa|ae)\s*[-:]\s*", "", name)
    name = re.sub(r"(?:\s+|[-_.]+)(?:hd|sd)$", "", name)
    return re.sub(r"[^a-z0-9\u0600-\u06ff]", "", name)


def time_value(value):
    try:
        return dt.datetime.strptime(value, "%Y%m%d%H%M%S %z")
    except (ValueError, TypeError):
        return None


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "NilesatEPG/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read(50_000_001)
    if len(body) > 50_000_000:
        raise ValueError("feed exceeds 50 MB compressed")
    return ET.fromstring(gzip.decompress(body) if body[:2] == b"\x1f\x8b" else body)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("services", type=Path, help="OpenWebif /web/getservices XML export")
    parser.add_argument("output", type=Path)
    parser.add_argument("--extra-xml", type=Path, action="append", default=[],
                        help="additional XMLTV file generated by iptv-org/epg")
    parser.add_argument("--aliases", type=Path, help="JSON map from XMLTV id to receiver channel name")
    parser.add_argument("--min-channels", type=int, default=1)
    parser.add_argument("--min-programmes", type=int, default=1)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    aliases = json.loads(args.aliases.read_text()) if args.aliases else {}
    services = []
    for item in ET.parse(args.services).getroot().iter("e2service"):
        name = item.findtext("e2servicename") or ""
        ref = item.findtext("e2servicereference") or ""
        if name and ref:
            services.append((name, ref))
    targets = collections.defaultdict(list)
    for name, ref in services:
        targets[key(name)].append((name, ref))

    now = dt.datetime.now(dt.timezone.utc)
    chosen = {}
    claimed = set()
    source_counts = collections.Counter()
    errors = {}
    feeds = FEEDS + [(path.name, path.resolve().as_uri()) for path in args.extra_xml]
    for label, url in feeds:
        try:
            root = fetch(url)
            names = collections.defaultdict(set)
            for channel in root.findall("channel"):
                if channel.get("id") in aliases:
                    names[key(aliases[channel.get("id")])].add(channel.get("id"))
                for display in channel.findall("display-name"):
                    if display.text:
                        names[key(display.text)].add(channel.get("id"))
            id_to_key = {next(iter(ids)): k for k, ids in names.items() if len(ids) == 1 and k in targets}
            candidates = collections.defaultdict(dict)
            for programme in root.findall("programme"):
                target = id_to_key.get(programme.get("channel"))
                if target is None or target in claimed:
                    continue
                start = time_value(programme.get("start"))
                stop = time_value(programme.get("stop"))
                title = (programme.findtext("title") or "").strip()
                if not start or not stop or stop <= now or start > now + dt.timedelta(days=7):
                    continue
                if stop <= start or title.casefold() in PLACEHOLDERS:
                    continue
                slot = (target, start.isoformat(), stop.isoformat())
                candidates[target][slot] = (label, title, programme.findtext("desc") or "")
            for target, programmes in candidates.items():
                chosen.update(programmes)
                claimed.add(target)
                source_counts[label] += len(programmes)
        except Exception as exc:
            errors[label] = str(exc)

    populated = {slot[0] for slot in chosen}
    if len(populated) < args.min_channels or len(chosen) < args.min_programmes:
        raise SystemExit(
            f"guide below required coverage: {len(populated)} channels, {len(chosen)} programmes"
        )

    tv = ET.Element("tv", {"generator-info-name": "Nilesat receiver guide"})
    for target in sorted(populated):
        channel = ET.SubElement(tv, "channel", {"id": "nilesat." + target})
        ET.SubElement(channel, "display-name").text = targets[target][0][0]
    for (target, start, stop), (source, title, desc) in sorted(chosen.items()):
        start_dt = dt.datetime.fromisoformat(start)
        stop_dt = dt.datetime.fromisoformat(stop)
        programme = ET.SubElement(tv, "programme", {
            "channel": "nilesat." + target,
            "start": start_dt.strftime("%Y%m%d%H%M%S %z"),
            "stop": stop_dt.strftime("%Y%m%d%H%M%S %z"),
        })
        ET.SubElement(programme, "title").text = title
        if desc:
            ET.SubElement(programme, "desc").text = desc
    ET.indent(tv)
    guide_tmp = args.output / "nilesat.xml.tmp"
    ET.ElementTree(tv).write(guide_tmp, encoding="utf-8", xml_declaration=True)
    guide_tmp.replace(args.output / "nilesat.xml")

    mapping = ET.Element("channels")
    for target in sorted(populated):
        channel = ET.SubElement(mapping, "channel", {"id": "nilesat." + target})
        channel.text = "\n" + "\n".join(ref for _, ref in targets[target]) + "\n"
    ET.indent(mapping)
    ET.ElementTree(mapping).write(args.output / "nilesat.channels.xml", encoding="utf-8", xml_declaration=True)

    report = {
        "generated_utc": now.isoformat(),
        "receiver_services": len(services),
        "unique_channel_names": len(targets),
        "channels_with_real_programmes": len(populated),
        "programmes": len(chosen),
        "programmes_by_source": dict(source_counts),
        "feed_errors": errors,
        "uncovered_names": sorted({name for k, rows in targets.items() if k not in populated for name, _ in rows}),
    }
    (args.output / "coverage.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({k: v for k, v in report.items() if k != "uncovered_names"}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
